+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Apr 27 00:22:18 2023 - INFO  - Start to run test.
+ facility_list=("auth" "daemon" "security" "lpr" "mail" "syslog" "news" "user" "uucp" "local1")
+ for facility in "${facility_list[@]}"
+ echo 'auth.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:22:19 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=39687
+ logger -t auth -p auth.info testauth39687
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testauth39687 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:22:24 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'daemon.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:22:25 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=46066
+ logger -t daemon -p daemon.info testdaemon46066
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testdaemon46066 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:22:31 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'security.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:22:32 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=52331
+ logger -t security -p security.info testsecurity52331
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testsecurity52331 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:22:37 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'lpr.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:22:38 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=58426
+ logger -t lpr -p lpr.info testlpr58426
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testlpr58426 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:22:43 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'mail.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:22:44 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=64545
+ logger -t mail -p mail.info testmail64545
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testmail64545 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:22:49 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'syslog.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:22:50 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=71094
+ logger -t syslog -p syslog.info testsyslog71094
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testsyslog71094 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:22:56 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'news.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:22:57 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=77466
+ logger -t news -p news.info testnews77466
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testnews77466 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:23:02 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'user.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:23:03 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=83889
+ logger -t user -p user.info testuser83889
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testuser83889 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:23:08 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'uucp.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:23:10 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=90128
+ logger -t uucp -p uucp.info testuucp90128
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testuucp90128 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:23:15 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ for facility in "${facility_list[@]}"
+ echo 'local1.*   /var/log/test'
oe_test_rsyslog_function_facility.sh: line 25: /etc/rsyslog.d/test.conf: No such file or directory
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 27'
+ message='oe_test_rsyslog_function_facility.sh line 27'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 27'
Thu Apr 27 00:23:16 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 27
+ '[' 0 -eq 1 ']'
+ return 0
++ date +%s%N
++ cut -c 9-13
+ time=96343
+ logger -t local1 -p local1.info testlocal196343
+ SLEEP_WAIT 3
+ wait_time=3
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 3 --cmd '' --mode 1
+ grep testlocal196343 /var/log/test
grep: /var/log/test: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rsyslog_function_facility.sh line 32'
+ message='oe_test_rsyslog_function_facility.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_rsyslog_function_facility.sh line 32'
Thu Apr 27 00:23:21 2023 - ERROR - oe_test_rsyslog_function_facility.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Apr 27 00:23:22 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 20
+ test 20 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Apr 27 00:23:23 2023 - ERROR - failed to execute the case.
+ exit 20
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Apr 27 00:23:24 2023 - INFO  - Start to restore the test environment.
+ rm -rf /var/log/test /etc/rsyslog.d/test.conf
+ systemctl restart rsyslog
Failed to restart rsyslog.service: Unit rsyslog.service not found.
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Apr 27 00:23:25 2023 - INFO  - End to restore the test environment.
