+ source ../common/common_lib.sh
++ source /root/GitRepo/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Apr  5 21:29:11 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'lxcfs lxcfs-tools'
+ pkgs='lxcfs lxcfs-tools'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py install --pkgs 'lxcfs lxcfs-tools' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpx5un08sv
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpx5un08sv
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Apr  5 21:30:58 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Apr  5 21:30:59 2023 - INFO  - Start testing...
+ test_execution lxcfs.service
+ service=lxcfs.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-04-05 21:30:59'
+ test_restart lxcfs.service
+ service=lxcfs.service
+ systemctl restart lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ CHECK_RESULT 1 0 0 'lxcfs.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service restart failed'
+ LOG_ERROR 'lxcfs.service restart failed'
+ message='lxcfs.service restart failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service restart failed'
Wed Apr  5 21:31:17 2023 - ERROR - lxcfs.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Wed Apr  5 21:31:17 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: active'
+ systemctl status lxcfs.service
+ CHECK_RESULT 1 0 0 'lxcfs.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service restart failed'
+ LOG_ERROR 'lxcfs.service restart failed'
+ message='lxcfs.service restart failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service restart failed'
Wed Apr  5 21:31:24 2023 - ERROR - lxcfs.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Wed Apr  5 21:31:25 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop lxcfs.service
+ CHECK_RESULT 0 0 0 'lxcfs.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status lxcfs.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'lxcfs.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service stop failed'
+ LOG_ERROR 'lxcfs.service stop failed'
+ message='lxcfs.service stop failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service stop failed'
Wed Apr  5 21:31:32 2023 - ERROR - lxcfs.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Wed Apr  5 21:31:33 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ CHECK_RESULT 1 0 0 'lxcfs.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service start failed'
+ LOG_ERROR 'lxcfs.service start failed'
+ message='lxcfs.service start failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service start failed'
Wed Apr  5 21:31:50 2023 - ERROR - lxcfs.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Wed Apr  5 21:31:51 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status lxcfs.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'lxcfs.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service start failed'
+ LOG_ERROR 'lxcfs.service start failed'
+ message='lxcfs.service start failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service start failed'
Wed Apr  5 21:31:58 2023 - ERROR - lxcfs.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Wed Apr  5 21:31:59 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled lxcfs.service
+ service=lxcfs.service
++ systemctl is-enabled lxcfs.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable lxcfs.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/lxcfs.service
+ find /etc/systemd/system/multi-user.target.wants/lxcfs.service
/etc/systemd/system/multi-user.target.wants/lxcfs.service
+ CHECK_RESULT 0 0 0 'lxcfs.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable lxcfs.service
Removed /etc/systemd/system/multi-user.target.wants/lxcfs.service.
+ find /etc/systemd/system/multi-user.target.wants/lxcfs.service
find: ‘/etc/systemd/system/multi-user.target.wants/lxcfs.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'lxcfs.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='lxcfs.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-04-05 21:30:59' -u lxcfs.service
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ grep -i 'fail\|error'
Apr 05 21:31:00 openeuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 21:31:16 openeuler-riscv64 lxcfs-tools[1391]: time="2023-04-05T21:31:16+08:00" level=error msg="lxcfs is not ready"
Apr 05 21:31:16 openeuler-riscv64 lxcfs-tools[1391]: time="2023-04-05T21:31:16+08:00" level=error msg="lxcfs is not ready"
Apr 05 21:31:16 openeuler-riscv64 systemd[1]: lxcfs.service: Failed with result 'exit-code'.
Apr 05 21:31:16 openeuler-riscv64 systemd[1]: Failed to start FUSE filesystem for LXC.
Apr 05 21:31:19 openeuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 21:31:25 openeuler-riscv64 systemd[1]: lxcfs.service: Failed with result 'exit-code'.
Apr 05 21:31:34 openeuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 21:31:50 openeuler-riscv64 lxcfs-tools[1645]: time="2023-04-05T21:31:50+08:00" level=error msg="lxcfs is not ready"
Apr 05 21:31:50 openeuler-riscv64 lxcfs-tools[1645]: time="2023-04-05T21:31:50+08:00" level=error msg="lxcfs is not ready"
Apr 05 21:31:50 openeuler-riscv64 systemd[1]: lxcfs.service: Failed with result 'exit-code'.
Apr 05 21:31:50 openeuler-riscv64 systemd[1]: Failed to start FUSE filesystem for LXC.
Apr 05 21:31:52 openeuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 21:32:08 openeuler-riscv64 lxcfs-tools[1768]: time="2023-04-05T21:32:08+08:00" level=error msg="lxcfs is not ready"
Apr 05 21:32:08 openeuler-riscv64 lxcfs-tools[1768]: time="2023-04-05T21:32:08+08:00" level=error msg="lxcfs is not ready"
Apr 05 21:32:09 openeuler-riscv64 systemd[1]: lxcfs.service: Failed with result 'exit-code'.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of lxcfs.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of lxcfs.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of lxcfs.service'
+ LOG_ERROR 'There is an error message for the log of lxcfs.service'
+ message='There is an error message for the log of lxcfs.service'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of lxcfs.service'
Wed Apr  5 21:32:10 2023 - ERROR - There is an error message for the log of lxcfs.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Wed Apr  5 21:32:11 2023 - ERROR - ../common/common_lib.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ sed -i 's\ExecStart=/usr/bin/lxcfs\ExecStart=/usr/bin/lxcfs -d\g' /usr/lib/systemd/system/lxcfs.service
+ systemctl daemon-reload
+ systemctl reload lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ CHECK_RESULT 1 0 0 'lxcfs.service reload failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service reload failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service reload failed'
+ LOG_ERROR 'lxcfs.service reload failed'
+ message='lxcfs.service reload failed'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service reload failed'
Wed Apr  5 21:32:50 2023 - ERROR - lxcfs.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_lxcfs.sh line 35'
+ message='oe_test_service_lxcfs.sh line 35'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_lxcfs.sh line 35'
Wed Apr  5 21:32:51 2023 - ERROR - oe_test_service_lxcfs.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl status lxcfs.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'lxcfs.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service reload causes the service status to change'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service reload causes the service status to change'
+ LOG_ERROR 'lxcfs.service reload causes the service status to change'
+ message='lxcfs.service reload causes the service status to change'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service reload causes the service status to change'
Wed Apr  5 21:32:52 2023 - ERROR - lxcfs.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_lxcfs.sh line 37'
+ message='oe_test_service_lxcfs.sh line 37'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_lxcfs.sh line 37'
Wed Apr  5 21:32:53 2023 - ERROR - oe_test_service_lxcfs.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Apr  5 21:32:53 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 21:32:54 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Apr  5 21:32:55 2023 - INFO  - start environment cleanup.
+ sed -i 'sExecStart=/usr/bin/lxcfs -d\ExecStart=/usr/bin/lxcfs\g' /usr/lib/systemd/system/lxcfs.service
sed: -e expression #1, char 55: unterminated `s' command
+ systemctl daemon-reload
+ systemctl reload lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ systemctl stop lxcfs.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpx5un08sv ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpx5un08sv
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Apr  5 21:33:34 2023 - INFO  - Finish environment cleanup!
