+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Fri Dec 30 11:43:03 2022 - INFO  - Start executing testcase.
+ echo -e 'Host "remote-server1"\nHostName 10.198.114.1\nUser root\nPort 22\n\nHost "remote-server2"\nHostName 10.198.114.3\nUser root\nPort 22'
+ expect
spawn ssh remote-server1
The authenticity of host '10.198.114.1 (10.198.114.1)' can't be established.
ED25519 key fingerprint is SHA256:3RWbr7G3eA+6iqLrtIHqJIWIJAgSwAsu+XHEn7q8mNo.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:1: 10.198.114.3
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '10.198.114.1' (ED25519) to the list of known hosts.
root@10.198.114.1's password: 
Last login: Fri Dec 30 11:21:45 2022 from ::1


Welcome to 5.10.0-9.oe2203.riscv64

System information as of time: 	Fri Dec 30 11:43:08 CST 2022

System load: 	[0;33;40m2.80[0m
Processes: 	118
Memory used: 	2.3%
Swap used: 	0.0%
Usage On: 	30%
IP address: 	10.198.114.1
IP address: 	10.0.2.15
Users online: 	1


[root@openEuler-riscv64 ~]# + CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ expect
spawn ssh remote-server2 11
root@10.198.114.3's password: 
bash: line 1: 11: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_sec_jump_login.sh line 59'
+ message='oe_test_sec_jump_login.sh line 59'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_sec_jump_login.sh line 59'
Fri Dec 30 11:43:32 2022 - ERROR - oe_test_sec_jump_login.sh line 59
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Fri Dec 30 11:43:33 2022 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Dec 30 11:43:34 2022 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Dec 30 11:43:35 2022 - INFO  - start environment cleanup.
+ rm /root/.ssh/config
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Dec 30 11:43:36 2022 - INFO  - Finish environment cleanup!
