+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Tue Nov 21 08:46:47 2023 - INFO  - Start executing testcase.
+ grep 'Authorized users only. All activities may be monitored and reported.' /etc/issue.net
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_warnings.sh line 25'
+ message='oe_test_ssh_warnings.sh line 25'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_warnings.sh line 25'
Tue Nov 21 08:46:48 2023 - ERROR - oe_test_ssh_warnings.sh line 25
+ '[' 0 -eq 1 ']'
+ return 0
+ expect
spawn ssh root@127.0.0.1
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ED25519 key fingerprint is SHA256:d3NEC93wlISSHHHavxHVwkwHLorEgd5Sljeqj8h17Zw.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.
root@127.0.0.1's password: 
Last login: Tue Nov 21 01:28:32 2023


Welcome to 6.1.19-2.oe2303.riscv64

System information as of time: 	Tue Nov 21 08:46:51 AM CST 2023

System load: 	[0;33;40m1.13[0m
Processes: 	113
Memory used: 	2.2%
Swap used: 	0.0%
Usage On: 	21%
IP address: 	192.168.114.3
IP address: 	10.0.2.15
Users online: 	1


[root@openeuler-riscv64 ~]# exit
logout
Connection to 127.0.0.1 closed.
+ grep 'Authorized users only. All activities may be monitored and reported' log
+ CHECK_RESULT 1 0 0 'remote login failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='remote login failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'remote login failed'
+ LOG_ERROR 'remote login failed'
+ message='remote login failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'remote login failed'
Tue Nov 21 08:46:51 2023 - ERROR - remote login failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ssh_warnings.sh line 48'
+ message='oe_test_ssh_warnings.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_ssh_warnings.sh line 48'
Tue Nov 21 08:46:52 2023 - ERROR - oe_test_ssh_warnings.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Tue Nov 21 08:46:52 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Nov 21 08:46:52 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Nov 21 08:46:53 2023 - INFO  - start environment cleanup.
+ rm -rf log
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Tue Nov 21 08:46:53 2023 - INFO  - Finish environment cleanup!
