+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Dec  6 07:10:55 2022 - INFO  - Start environmental preparation.
+ sudo systemctl start firewalld
A dependency job for firewalld.service failed. See 'journalctl -xe' for details.
++ echo localhost.0.0
+ source_ip=localhost.0.0
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Dec  6 07:10:56 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Tue Dec  6 07:10:57 2022 - INFO  - Start executing testcase.
+ sudo firewall-cmd --zone=public --add-rich-rule 'rule family=ipv4 source address=localhost.0.0/16 accept'
Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
+ CHECK_RESULT 36
+ actual_result=36
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 36 ']'
+ '[' 0 -eq 0 ']'
+ test 36x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_richrule_blacklist.sh line 32'
+ message='oe_test_firewalld_richrule_blacklist.sh line 32'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_richrule_blacklist.sh line 32'
Tue Dec  6 07:11:01 2022 - ERROR - oe_test_firewalld_richrule_blacklist.sh line 32
+ return 0
+ SSH_CMD 'echo test | nc localhost 5555' '' '' ''
+ nc -l -p 5555
+ cmd='echo test | nc localhost 5555'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo test | nc localhost 5555' -i '' -u '' -p '' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Dec  6 07:11:02 2022 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_richrule_blacklist.sh line 35'
+ message='oe_test_firewalld_richrule_blacklist.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_richrule_blacklist.sh line 35'
Tue Dec  6 07:11:03 2022 - ERROR - oe_test_firewalld_richrule_blacklist.sh line 35
+ return 0
+ grep test /tmp/tmp_log
oe_test_firewalld_richrule_blacklist.sh: line 33: nc: command not found
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ sudo firewall-cmd --zone=public --remove-rich-rule 'rule family=ipv4 source address=localhost.0.0/16 accept'
Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
+ CHECK_RESULT 36
+ actual_result=36
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 36 ']'
+ '[' 0 -eq 0 ']'
+ test 36x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_richrule_blacklist.sh line 41'
+ message='oe_test_firewalld_richrule_blacklist.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_richrule_blacklist.sh line 41'
Tue Dec  6 07:11:07 2022 - ERROR - oe_test_firewalld_richrule_blacklist.sh line 41
+ return 0
+ SSH_CMD 'echo test | nc localhost 5555' '' '' ''
+ cmd='echo test | nc localhost 5555'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo test | nc localhost 5555' -i '' -u '' -p '' -t 300 -o 22
+ nc -l -p 5555
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Dec  6 07:11:08 2022 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 1
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log=
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ sudo firewall-cmd --zone=public --add-rich-rule 'rule family=ipv4 source address=localhost.0.0/16 accept'
Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
+ CHECK_RESULT 36
+ actual_result=36
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 36 ']'
+ '[' 0 -eq 0 ']'
+ test 36x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_richrule_blacklist.sh line 47'
+ message='oe_test_firewalld_richrule_blacklist.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_richrule_blacklist.sh line 47'
Tue Dec  6 07:11:12 2022 - ERROR - oe_test_firewalld_richrule_blacklist.sh line 47
+ return 0
+ SSH_CMD 'echo test | nc localhost 5555' '' '' ''
+ cmd='echo test | nc localhost 5555'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo test | nc localhost 5555' -i '' -u '' -p '' -t 300 -o 22
+ nc -l -p 5555
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Dec  6 07:11:13 2022 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 0
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_richrule_blacklist.sh line 50'
+ message='oe_test_firewalld_richrule_blacklist.sh line 50'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_richrule_blacklist.sh line 50'
Tue Dec  6 07:11:13 2022 - ERROR - oe_test_firewalld_richrule_blacklist.sh line 50
+ return 0
+ grep test /tmp/tmp_log
oe_test_firewalld_richrule_blacklist.sh: line 48: nc: command not found
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ sudo firewall-cmd --zone=public --add-rich-rule 'rule family=ipv4 source address=localhost.0.0/16 drop'
Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
+ CHECK_RESULT 36
+ actual_result=36
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 36 ']'
+ '[' 0 -eq 0 ']'
+ test 36x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_firewalld_richrule_blacklist.sh line 56'
+ message='oe_test_firewalld_richrule_blacklist.sh line 56'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_firewalld_richrule_blacklist.sh line 56'
Tue Dec  6 07:11:18 2022 - ERROR - oe_test_firewalld_richrule_blacklist.sh line 56
+ return 0
+ SSH_CMD 'echo test | nc localhost 5555' '' '' ''
+ cmd='echo test | nc localhost 5555'
+ remoteip=
+ remotepasswd=
+ remoteuser=
+ timeout=300
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshcmd.sh -c 'echo test | nc localhost 5555' -i '' -u '' -p '' -t 300 -o 22
+ nc -l -p 5555
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Tue Dec  6 07:11:19 2022 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1 0 1
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log=
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Tue Dec  6 07:11:19 2022 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Dec  6 07:11:20 2022 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Dec  6 07:11:21 2022 - INFO  - start environment cleanup.
+ sudo firewall-cmd --zone=public --remove-rich-rule 'rule family=ipv4 source address=localhost.0.0/16 accept'
Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
+ sudo firewall-cmd --zone=public --remove-rich-rule 'rule family=ipv4 source address=localhost.0.0/16 drop'
Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
+ sudo firewall-cmd --reload
Error: DBUS_ERROR: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
+ sudo systemctl start firewalld
A dependency job for firewalld.service failed. See 'journalctl -xe' for details.
+ rm -rf /tmp/tmp_log
++ pgrep -f 'nc -l -p 5555'
+ kill -9 735
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Tue Dec  6 07:11:32 2022 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Tue Dec  6 07:11:33 2022 - INFO  - Finish environment cleanup!
