+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment'
+ message='Start to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment'
Wed Nov 22 08:50:20 2023 - INFO  - Start to prepare the test environment
+ DNF_INSTALL intel-cmt-cat
+ pkgs=intel-cmt-cat
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs intel-cmt-cat --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 1 day, 7:01:29 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: intel-cmt-cat
Error: Unable to find a match: intel-cmt-cat'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 1 day, 7:01:29 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: intel-cmt-cat
Error: Unable to find a match: intel-cmt-cat'
+ LOG_INFO 'End to prepare the test environment'
+ message='End to prepare the test environment'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment'
Wed Nov 22 08:50:45 2023 - INFO  - End to prepare the test environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Nov 22 08:50:45 2023 - INFO  - Start to run test.
+ pqos -h
+ grep -e 'Usage: pqos'
oe_test_intel_cmt_cat.sh: line 30: pqos: command not found
+ CHECK_RESULT 1 0 0 'L31: -h No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L31: -h No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L31: -h No Pass'
+ LOG_ERROR 'L31: -h No Pass'
+ message='L31: -h No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L31: -h No Pass'
Wed Nov 22 08:50:46 2023 - ERROR - L31: -h No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_intel_cmt_cat.sh line 31'
+ message='oe_test_intel_cmt_cat.sh line 31'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_intel_cmt_cat.sh line 31'
Wed Nov 22 08:50:46 2023 - ERROR - oe_test_intel_cmt_cat.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ pqos -s
+ grep -e 'L3CA COS definitions'
oe_test_intel_cmt_cat.sh: line 32: pqos: command not found
+ CHECK_RESULT 1 0 0 'L33: -s No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L33: -s No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L33: -s No Pass'
+ LOG_ERROR 'L33: -s No Pass'
+ message='L33: -s No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L33: -s No Pass'
Wed Nov 22 08:50:47 2023 - ERROR - L33: -s No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_intel_cmt_cat.sh line 33'
+ message='oe_test_intel_cmt_cat.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_intel_cmt_cat.sh line 33'
Wed Nov 22 08:50:47 2023 - ERROR - oe_test_intel_cmt_cat.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ pqos -d
+ grep 'Hardware capabilities'
oe_test_intel_cmt_cat.sh: line 34: pqos: command not found
+ CHECK_RESULT 1 0 0 'L35: -d No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L35: -d No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L35: -d No Pass'
+ LOG_ERROR 'L35: -d No Pass'
+ message='L35: -d No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L35: -d No Pass'
Wed Nov 22 08:50:47 2023 - ERROR - L35: -d No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_intel_cmt_cat.sh line 35'
+ message='oe_test_intel_cmt_cat.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_intel_cmt_cat.sh line 35'
Wed Nov 22 08:50:48 2023 - ERROR - oe_test_intel_cmt_cat.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ pqos -f common/alloc_reset_cat.cfg
oe_test_intel_cmt_cat.sh: line 36: pqos: command not found
+ grep -e 'Allocation reset successful'
+ CHECK_RESULT 1 0 0 'L37: -f No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L37: -f No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L37: -f No Pass'
+ LOG_ERROR 'L37: -f No Pass'
+ message='L37: -f No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L37: -f No Pass'
Wed Nov 22 08:50:48 2023 - ERROR - L37: -f No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_intel_cmt_cat.sh line 37'
+ message='oe_test_intel_cmt_cat.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_intel_cmt_cat.sh line 37'
Wed Nov 22 08:50:49 2023 - ERROR - oe_test_intel_cmt_cat.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ pqos --version
+ grep 'PQoS Library version:'
oe_test_intel_cmt_cat.sh: line 38: pqos: command not found
+ CHECK_RESULT 1 0 0 'L39: --version No Pass'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='L39: --version No Pass'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'L39: --version No Pass'
+ LOG_ERROR 'L39: --version No Pass'
+ message='L39: --version No Pass'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'L39: --version No Pass'
Wed Nov 22 08:50:49 2023 - ERROR - L39: --version No Pass
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_intel_cmt_cat.sh line 39'
+ message='oe_test_intel_cmt_cat.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_intel_cmt_cat.sh line 39'
Wed Nov 22 08:50:50 2023 - ERROR - oe_test_intel_cmt_cat.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Nov 22 08:50:50 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Nov 22 08:50:51 2023 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Nov 22 08:50:51 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 1 day, 7:01:29 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: intel-cmt-cat
Error: Unable to find a match: intel-cmt-cat ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 1 day, 7:01:29 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: intel-cmt-cat
Error: Unable to find a match: intel-cmt-cat'
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 192, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 163, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Last metadata expiration check: 1 day, 7:01:29 ago on Tue 21 Nov 2023 01:49:15 AM CST.\nNo match for argument: intel-cmt-cat\nError: Unable to find a match: intel-cmt-cat'
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Nov 22 08:50:54 2023 - INFO  - End to restore the test environment.
