+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start loading data!'
+ message='Start loading data!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start loading data!'
Wed Nov 22 01:15:23 2023 - INFO  - Start loading data!
++ TEST_DISK 1
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ TEST_DISK=/dev/vdb
+ LOG_INFO 'Loading data is complete!'
+ message='Loading data is complete!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Loading data is complete!'
Wed Nov 22 01:15:29 2023 - INFO  - Loading data is complete!
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Nov 22 01:15:30 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'tang clevis clevis-dracut cryptsetup-reencrypt clevis-udisks2'
+ pkgs='tang clevis clevis-dracut cryptsetup-reencrypt clevis-udisks2'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'tang clevis clevis-dracut cryptsetup-reencrypt clevis-udisks2' --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt'
+ DNF_INSTALL tang 2
+ pkgs=tang
+ node=2
+ '[' -z 'Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt' ']'
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs tang --node 2 --tempfile 'Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt'
+ tmpfile2='Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt'
+ '[' -z 'Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt' ']'
+ fdisk /dev/vdb
+ echo -e 'n\n\np\n\n\n+100M\nw'

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0x41390a71.

Command (m for help): Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): 
Using default response p.
Partition number (1-4, default 1): Value out of range.
Partition number (1-4, default 1): First sector (2048-20971519, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-20971519, default 20971519): 
Created a new partition 1 of type 'Linux' and of size 100 MiB.

Command (m for help): The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

+ ls /mnt/test_encrypted
ls: cannot access '/mnt/test_encrypted': No such file or directory
+ mkdir /mnt/test_encrypted
+ ls /etc/systemd/system/tangd.socket.d
ls: cannot access '/etc/systemd/system/tangd.socket.d': No such file or directory
+ SOCKET_CONTENT='[Socket]\nListenStream=\nListenStream=8009'
+ mkdir /etc/systemd/system/tangd.socket.d
+ echo -e '[Socket]\nListenStream=\nListenStream=8009'
++ uuidgen
+ UUID=13a74b04-f907-49c0-a7a6-263896925484
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Nov 22 01:16:42 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Wed Nov 22 01:16:42 2023 - INFO  - Start executing testcase.
+ echo -e '\n\n'
+ cryptsetup-reencrypt --type luks1 --new --reduce-device-size 8M /dev/vdb1
oe_test_high_nbde.sh: line 44: cryptsetup-reencrypt: command not found
+ CHECK_RESULT 127 0 0 'Disk encryption failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Disk encryption failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Disk encryption failed'
+ LOG_ERROR 'Disk encryption failed'
+ message='Disk encryption failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Disk encryption failed'
Wed Nov 22 01:16:43 2023 - ERROR - Disk encryption failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 45'
+ message='oe_test_high_nbde.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 45'
Wed Nov 22 01:16:43 2023 - ERROR - oe_test_high_nbde.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ echo -e '\n'
+ cryptsetup open /dev/vdb1 test_encrypted
oe_test_high_nbde.sh: line 46: cryptsetup: command not found
+ CHECK_RESULT 127 0 0 'Disk mapping failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Disk mapping failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Disk mapping failed'
+ LOG_ERROR 'Disk mapping failed'
+ message='Disk mapping failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Disk mapping failed'
Wed Nov 22 01:16:44 2023 - ERROR - Disk mapping failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 47'
+ message='oe_test_high_nbde.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 47'
Wed Nov 22 01:16:45 2023 - ERROR - oe_test_high_nbde.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ mkfs.ext4 /dev/mapper/test_encrypted -F
mke2fs 1.46.5 (30-Dec-2021)
The file /dev/mapper/test_encrypted does not exist and no size was specified.
+ mount /dev/mapper/test_encrypted /mnt/test_encrypted
mount: /mnt/test_encrypted: special device /dev/mapper/test_encrypted does not exist.
+ CHECK_RESULT 32 0 0 'Disk mount failed'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='Disk mount failed'
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'Disk mount failed'
+ LOG_ERROR 'Disk mount failed'
+ message='Disk mount failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Disk mount failed'
Wed Nov 22 01:16:45 2023 - ERROR - Disk mount failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 50'
+ message='oe_test_high_nbde.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 50'
Wed Nov 22 01:16:46 2023 - ERROR - oe_test_high_nbde.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ cryptsetup luksHeaderBackup /dev/vdb1 --header-backup-file /tmp/header.bin
oe_test_high_nbde.sh: line 51: cryptsetup: command not found
+ CHECK_RESULT 127 0 0 'Backup luksHeader information failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Backup luksHeader information failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Backup luksHeader information failed'
+ LOG_ERROR 'Backup luksHeader information failed'
+ message='Backup luksHeader information failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Backup luksHeader information failed'
Wed Nov 22 01:16:46 2023 - ERROR - Backup luksHeader information failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 52'
+ message='oe_test_high_nbde.sh line 52'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 52'
Wed Nov 22 01:16:47 2023 - ERROR - oe_test_high_nbde.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 2
+ wait_time=2
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 2 --cmd '' --mode 1
+ systemctl enable tangd.socket
Failed to enable unit: Unit file tangd.socket does not exist.
+ CHECK_RESULT 1 0 0 'Failed to enable tangd.socket service'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to enable tangd.socket service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to enable tangd.socket service'
+ LOG_ERROR 'Failed to enable tangd.socket service'
+ message='Failed to enable tangd.socket service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to enable tangd.socket service'
Wed Nov 22 01:16:50 2023 - ERROR - Failed to enable tangd.socket service
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 55'
+ message='oe_test_high_nbde.sh line 55'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 55'
Wed Nov 22 01:16:50 2023 - ERROR - oe_test_high_nbde.sh line 55
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl daemon-reload
+ grep 8009
+ systemctl show tangd.socket -p Listen
+ CHECK_RESULT 1 0 0 'Failed to display the '\''Listen'\'' property of tangd.socket'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to display the '\''Listen'\'' property of tangd.socket'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to display the '\''Listen'\'' property of tangd.socket'
+ LOG_ERROR 'Failed to display the '\''Listen'\'' property of tangd.socket'
+ message='Failed to display the '\''Listen'\'' property of tangd.socket'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to display the '\''Listen'\'' property of tangd.socket'
Wed Nov 22 01:16:55 2023 - ERROR - Failed to display the 'Listen' property of tangd.socket
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 58'
+ message='oe_test_high_nbde.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 58'
Wed Nov 22 01:16:55 2023 - ERROR - oe_test_high_nbde.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start tangd.socket
Failed to start tangd.socket: Unit tangd.socket not found.
+ CHECK_RESULT 5 0 0 'Failed to start tangd.socket service'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='Failed to start tangd.socket service'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'Failed to start tangd.socket service'
+ LOG_ERROR 'Failed to start tangd.socket service'
+ message='Failed to start tangd.socket service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to start tangd.socket service'
Wed Nov 22 01:16:56 2023 - ERROR - Failed to start tangd.socket service
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_high_nbde.sh line 60'
+ message='oe_test_high_nbde.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_high_nbde.sh line 60'
Wed Nov 22 01:16:56 2023 - ERROR - oe_test_high_nbde.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_CMD 'systemctl enable tangd.socket;mkdir /etc/systemd/system/tangd.socket.d' 192.168.114.7 'openEuler12#$' root
+ cmd='systemctl enable tangd.socket;mkdir /etc/systemd/system/tangd.socket.d'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl enable tangd.socket;mkdir /etc/systemd/system/tangd.socket.d' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
Wed Nov 22 01:16:57 2023 - WARN  - the remote user uses the default configuration.
Wed Nov 22 01:16:58 2023 - WARN  - the remote password uses the default configuration.
Wed Nov 22 01:16:58 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@192.168.114.7 systemctl enable tangd.socket;mkdir /etc/systemd/system/tangd.socket.d
The authenticity of host '192.168.114.7 (192.168.114.7)' can't be established.
ED25519 key fingerprint is SHA256:d3NEC93wlISSHHHavxHVwkwHLorEgd5Sljeqj8h17Zw.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.114.7' (ED25519) to the list of known hosts.
root@192.168.114.7's password: 
Created symlink /etc/systemd/system/multi-user.target.wants/tangd.socket → /usr/lib/systemd/system/tangd.socket.
+ ret=0
+ test 0 -ne 0
+ return 0
+ P_SSH_CMD --node 2 --cmd 'echo -e [Socket]\\nListenStream=\\nListenStream=8009 > /etc/systemd/system/tangd.socket.d/override.conf'
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --node 2 --cmd 'echo -e [Socket]\\nListenStream=\\nListenStream=8009 > /etc/systemd/system/tangd.socket.d/override.conf'

+ SSH_CMD 'systemctl daemon-reload;systemctl show tangd.socket -p Listen | grep 8009;
    		systemctl start tangd.socket;systemctl stop firewalld;setenforce 0' 192.168.114.7 'openEuler12#$' root
+ cmd='systemctl daemon-reload;systemctl show tangd.socket -p Listen | grep 8009;
    		systemctl start tangd.socket;systemctl stop firewalld;setenforce 0'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl daemon-reload;systemctl show tangd.socket -p Listen | grep 8009;
    		systemctl start tangd.socket;systemctl stop firewalld;setenforce 0' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
Wed Nov 22 01:17:09 2023 - WARN  - the remote user uses the default configuration.
Wed Nov 22 01:17:09 2023 - WARN  - the remote password uses the default configuration.
Wed Nov 22 01:17:10 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@192.168.114.7 systemctl daemon-reload;systemctl show tangd.socket -p Listen | grep 8009;
    		systemctl start tangd.socket;systemctl stop firewalld;setenforce 0
root@192.168.114.7's password: 
Listen=[::]:8009 (Stream)
Failed to stop firewalld.service: Unit firewalld.service not loaded.
setenforce: SELinux is disabled
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Wed Nov 22 01:17:20 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ curl http://127.0.0.1:8009/adv -o adv.jws
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 8009 after 7 ms: Couldn't connect to server
+ SLEEP_WAIT 1
+ wait_time=1
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 1 --cmd '' --mode 1
+ expect '-c
        set timeout 120
        spawn luksmeta init -n -d /dev/vdb1
	expect {
		"yn" {
			send "y\r"
			exp_continue
		}
		timeout
	}
    '
spawn luksmeta init -n -d /dev/vdb1
couldn't execute "luksmeta": no such file or directory
    while executing
"spawn luksmeta init -n -d /dev/vdb1"
+ CHECK_RESULT 0 0 0 'luksmeta init failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='luksmeta init failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ echo
+ luksmeta save -d /dev/vdb1 -s 0 -u 13a74b04-f907-49c0-a7a6-263896925484
oe_test_high_nbde.sh: line 79: luksmeta: command not found
+ expect '-c
	set timeout 120
        spawn clevis luks bind -d /dev/vdb1 sss '\''{"t":1,"pins":{"tang":[{"url":"http://127.0.0.1:8009"},{"url":"http://192.168.114.7:8009"}]}}'\''
	    expect {
		"ynYN" {
			send "y\r"
			exp_continue
		}
		"yn" {
            send "y\r"
            exp_continue
            }
		"assword" {
            send "\r"
            exp_continue
        }
		timeout
	}
'
extra characters after close-brace
    while executing
"spawn clevis luks bind -d /dev/vdb1 sss '{"t":1,"pins":{"tang":[{"url":"http://127.0.0.1:8009"},"
+ CHECK_RESULT 0 0 0 'Disk binding failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Disk binding failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ expect '-c
        set timeout 120
        spawn clevis luks unbind -d /dev/vdb1 -s 1
	    expect {
		"yn" {
			send "y\r"
			exp_continue
		}
		timeout
	}
    '
spawn clevis luks unbind -d /dev/vdb1 -s 1
couldn't execute "clevis": no such file or directory
    while executing
"spawn clevis luks unbind -d /dev/vdb1 -s 1"
+ CHECK_RESULT 0 0 0 'Disk unbinding failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Disk unbinding failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Wed Nov 22 01:17:23 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Nov 22 01:17:24 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Nov 22 01:17:24 2023 - INFO  - start environment cleanup.
+ umount /mnt/test_encrypted
umount: /mnt/test_encrypted: not mounted.
+ cryptsetup close test_encrypted
oe_test_high_nbde.sh: line 118: cryptsetup: command not found
+ mkfs.ext4 /dev/vdb1 -F
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:      0/102400             done                            
Creating filesystem with 102400 1k blocks and 25584 inodes
Filesystem UUID: 6e1ebd9a-f0e1-4c4b-a273-2f5a07c1204c
Superblock backups stored on blocks: 
	8193, 24577, 40961, 57345, 73729

Allocating group tables:  0/13     done                            
Writing inode tables:  0/13     done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information:  0/13     done

+ fdisk /dev/vdb
+ echo -e 'd\n\nw'

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): Selected partition 1
Partition 1 has been deleted.

Command (m for help): 

Command (m for help): 
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt'
+ '[' 0 -ne 0 ']'
+ rm -rf secert.jwe adv.jws sec.jwe input-plain.txt /etc/systemd/system/tangd.socket.d /mnt/test_encrypted1 /var/db/tang /tmp/header.bin
+ DNF_REMOVE 2 tang
+ node=2
+ pkg_list=tang
+ mode=0
+ [[ -z Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt ]]
+ '[' 0 -ne 0 ']'
+ '[' 2 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 2 --pkgs tang --tempfile 'Last metadata expiration check: 23:26:42 ago on Tue 21 Nov 2023 01:49:15 AM CST.
No match for argument: cryptsetup-reencrypt
Error: Unable to find a match: cryptsetup-reencrypt'
+ '[' 0 -ne 0 ']'
+ SSH_CMD 'rm -rf /etc/systemd/system/tangd.socket.d /var/db/tang' 192.168.114.7 'openEuler12#$' root
+ cmd='rm -rf /etc/systemd/system/tangd.socket.d /var/db/tang'
+ remoteip=192.168.114.7
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'rm -rf /etc/systemd/system/tangd.socket.d /var/db/tang' -i 192.168.114.7 -u root -p 'openEuler12#$' -t 300 -o 22
Wed Nov 22 01:17:48 2023 - WARN  - the remote user uses the default configuration.
Wed Nov 22 01:17:49 2023 - WARN  - the remote password uses the default configuration.
Wed Nov 22 01:17:49 2023 - WARN  - the connect port using the default configuration
spawn ssh -o ConnectTimeout=300 -p 22 root@192.168.114.7 rm -rf /etc/systemd/system/tangd.socket.d /var/db/tang
root@192.168.114.7's password: 
+ ret=0
+ test 0 -ne 0
+ return 0
+ mkfs.ext4 /dev/vdb -F
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks:       0/2621440               done                            
Creating filesystem with 2621440 4k blocks and 655360 inodes
Filesystem UUID: f4744d13-c781-4e15-a344-27cde6ba2624
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables:  0/80     done                            
Writing inode tables:  0/80     done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/80     done

+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Nov 22 01:17:52 2023 - INFO  - Finish environment cleanup!
