+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Nov 22 05:01:25 2023 - INFO  - Start to prepare the test environment.
+ mkdir /tmp/pigz /tmp/pigz/pigz01
+ touch /tmp/pigz/1.txt /tmp/pigz/pigz01/1.txt
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Nov 22 05:01:26 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ pigz -9 /tmp/pigz/1.txt
oe_test_pigz_02.sh: line 30: pigz: command not found
+ test -e /tmp/pigz/1.txt.gz
+ CHECK_RESULT 1 0 0 'pigz -9 command execution failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pigz -9 command execution failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pigz -9 command execution failure'
+ LOG_ERROR 'pigz -9 command execution failure'
+ message='pigz -9 command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -9 command execution failure'
Wed Nov 22 05:01:26 2023 - ERROR - pigz -9 command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_02.sh line 32'
+ message='oe_test_pigz_02.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_02.sh line 32'
Wed Nov 22 05:01:27 2023 - ERROR - oe_test_pigz_02.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ pigz -l /tmp/pigz/1.txt.gz
oe_test_pigz_02.sh: line 33: pigz: command not found
+ CHECK_RESULT 127 0 0 'pigz -l command execution failure'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='pigz -l command execution failure'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'pigz -l command execution failure'
+ LOG_ERROR 'pigz -l command execution failure'
+ message='pigz -l command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -l command execution failure'
Wed Nov 22 05:01:27 2023 - ERROR - pigz -l command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_02.sh line 34'
+ message='oe_test_pigz_02.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_02.sh line 34'
Wed Nov 22 05:01:28 2023 - ERROR - oe_test_pigz_02.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ pigz -L
oe_test_pigz_02.sh: line 35: pigz: command not found
+ CHECK_RESULT 127 0 0 'pigz -L command execution failure'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='pigz -L command execution failure'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'pigz -L command execution failure'
+ LOG_ERROR 'pigz -L command execution failure'
+ message='pigz -L command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -L command execution failure'
Wed Nov 22 05:01:28 2023 - ERROR - pigz -L command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_02.sh line 36'
+ message='oe_test_pigz_02.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_02.sh line 36'
Wed Nov 22 05:01:29 2023 - ERROR - oe_test_pigz_02.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ pigz -f /tmp/pigz/1.txt.gz
oe_test_pigz_02.sh: line 37: pigz: command not found
+ test -e /tmp/pigz/1.txt.gz.gz
+ CHECK_RESULT 1 0 0 'pigz -f command execution failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='pigz -f command execution failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'pigz -f command execution failure'
+ LOG_ERROR 'pigz -f command execution failure'
+ message='pigz -f command execution failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'pigz -f command execution failure'
Wed Nov 22 05:01:29 2023 - ERROR - pigz -f command execution failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_pigz_02.sh line 39'
+ message='oe_test_pigz_02.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_pigz_02.sh line 39'
Wed Nov 22 05:01:29 2023 - ERROR - oe_test_pigz_02.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Nov 22 05:01:30 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Nov 22 05:01:30 2023 - INFO  - Start to restore the test environment.
+ rm -rf /tmp/pigz
+ LOG_INFO 'Finish restoring the test environment.'
+ message='Finish restoring the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish restoring the test environment.'
Wed Nov 22 05:01:31 2023 - INFO  - Finish restoring the test environment.
