+ source ../common/storage_disk_lib.sh
++ source /root/GitRepo/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Thu Apr  6 15:14:22 2023 - INFO  - Start environment preparation.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/GitRepo/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=vdb
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ pvcreate /dev/ -y
  No device found for /dev/.
+ vgcreate openeulertest /dev/ -y
  No device found for /dev/.
+ vgextend openeulertest /dev/vdb -y
  Physical volume "/dev/vdb" successfully created.
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ vgextend openeulertest /dev/ -y
  No device found for /dev/.
+ vgextend openeulertest /dev/ -y
  No device found for /dev/.
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Thu Apr  6 15:14:35 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Thu Apr  6 15:14:36 2023 - INFO  - Start executing testcase!
+ expect -c '
    set timeout 30
    log_file testlog
    spawn lvcreate --type raid10 -i 2 -m 1 -L 50MB --maxrecoveryrate 128 -n test openeulertest
    expect "*\[y/n\]*" {send "y\r"}
    expect eof
'
spawn lvcreate --type raid10 -i 2 -m 1 -L 50MB --maxrecoveryrate 128 -n test openeulertest
modprobe: FATAL: Module dm-raid not found in directory /lib/modules/6.1.8-3.oe2303.riscv64
  /usr/sbin/modprobe failed: 1
y
  raid10: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.
+ grep -iE 'fail|error' testlog
  /usr/sbin/modprobe failed: 1
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_limit.sh line 41'
+ message='oe_test_storage_lvm_set_limit.sh line 41'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_limit.sh line 41'
Thu Apr  6 15:14:38 2023 - ERROR - oe_test_storage_lvm_set_limit.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ grep /dev/openeulertest/test
+ lvscan
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_limit.sh line 43'
+ message='oe_test_storage_lvm_set_limit.sh line 43'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_limit.sh line 43'
Thu Apr  6 15:14:39 2023 - ERROR - oe_test_storage_lvm_set_limit.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Thu Apr  6 15:14:40 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Apr  6 15:14:41 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Apr  6 15:14:42 2023 - INFO  - start environment cleanup.
+ lvremove -y openeulertest/test
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ vgremove -y openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ pvremove /dev/ /dev/ /dev/vdb /dev/
  No device found for /dev/.
  No device found for /dev/.
  No device found for /dev/.
  Labels on physical volume "/dev/vdb" successfully wiped.
+ rm -rf testlog
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Thu Apr  6 15:14:44 2023 - INFO  - Finish environment cleanup.
