+ source /root/GitRepo/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Apr  5 14:09:57 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL groovy
+ pkgs=groovy
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py install --pkgs groovy --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 14:08:03 ago on Wed 05 Apr 2023 12:02:19 AM CST.
Error: 
 Problem: conflicting requests
  - nothing provides mvn(jline:jline) needed by groovy-2.4.8-11.oe2303.noarch
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 14:08:03 ago on Wed 05 Apr 2023 12:02:19 AM CST.
Error: 
 Problem: conflicting requests
  - nothing provides mvn(jline:jline) needed by groovy-2.4.8-11.oe2303.noarch
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
+ cp ../common/test.groovy ./
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Apr  5 14:10:24 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Apr  5 14:10:25 2023 - INFO  - Start to run test.
+ groovyc -d /tmp/ test.groovy
oe_test_groovy_02.sh: line 30: groovyc: command not found
+ CHECK_RESULT 127 0 0 'Check groovyc -d failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check groovyc -d failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check groovyc -d failed.'
+ LOG_ERROR 'Check groovyc -d failed.'
+ message='Check groovyc -d failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc -d failed.'
Wed Apr  5 14:10:26 2023 - ERROR - Check groovyc -d failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 31'
+ message='oe_test_groovy_02.sh line 31'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 31'
Wed Apr  5 14:10:26 2023 - ERROR - oe_test_groovy_02.sh line 31
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /tmp/test.class
+ CHECK_RESULT 1 0 0 'Check groovyc -d failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovyc -d failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovyc -d failed.'
+ LOG_ERROR 'Check groovyc -d failed.'
+ message='Check groovyc -d failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc -d failed.'
Wed Apr  5 14:10:27 2023 - ERROR - Check groovyc -d failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 33'
+ message='oe_test_groovy_02.sh line 33'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 33'
Wed Apr  5 14:10:28 2023 - ERROR - oe_test_groovy_02.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ groovyc test.groovy
oe_test_groovy_02.sh: line 34: groovyc: command not found
+ CHECK_RESULT 127 0 0 'Check groovyc failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check groovyc failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check groovyc failed.'
+ LOG_ERROR 'Check groovyc failed.'
+ message='Check groovyc failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc failed.'
Wed Apr  5 14:10:29 2023 - ERROR - Check groovyc failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 35'
+ message='oe_test_groovy_02.sh line 35'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 35'
Wed Apr  5 14:10:29 2023 - ERROR - oe_test_groovy_02.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f test.class
+ groovyc -e test.groovy
oe_test_groovy_02.sh: line 37: groovyc: command not found
+ CHECK_RESULT 127 0 0 'Check groovyc -e failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check groovyc -e failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check groovyc -e failed.'
+ LOG_ERROR 'Check groovyc -e failed.'
+ message='Check groovyc -e failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc -e failed.'
Wed Apr  5 14:10:30 2023 - ERROR - Check groovyc -e failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 38'
+ message='oe_test_groovy_02.sh line 38'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 38'
Wed Apr  5 14:10:31 2023 - ERROR - oe_test_groovy_02.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f test.class
+ CHECK_RESULT 1 0 0 'Check groovyc -e failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovyc -e failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovyc -e failed.'
+ LOG_ERROR 'Check groovyc -e failed.'
+ message='Check groovyc -e failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc -e failed.'
Wed Apr  5 14:10:32 2023 - ERROR - Check groovyc -e failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 40'
+ message='oe_test_groovy_02.sh line 40'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 40'
Wed Apr  5 14:10:33 2023 - ERROR - oe_test_groovy_02.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ groovyc -cp lib/dep.jar test.groovy
oe_test_groovy_02.sh: line 41: groovyc: command not found
+ CHECK_RESULT 127 0 0 'Check groovyc -cp failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check groovyc -cp failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check groovyc -cp failed.'
+ LOG_ERROR 'Check groovyc -cp failed.'
+ message='Check groovyc -cp failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc -cp failed.'
Wed Apr  5 14:10:33 2023 - ERROR - Check groovyc -cp failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 42'
+ message='oe_test_groovy_02.sh line 42'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 42'
Wed Apr  5 14:10:34 2023 - ERROR - oe_test_groovy_02.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f test.class
+ CHECK_RESULT 1 0 0 'Check groovyc -cp failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovyc -cp failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovyc -cp failed.'
+ LOG_ERROR 'Check groovyc -cp failed.'
+ message='Check groovyc -cp failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc -cp failed.'
Wed Apr  5 14:10:35 2023 - ERROR - Check groovyc -cp failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 44'
+ message='oe_test_groovy_02.sh line 44'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 44'
Wed Apr  5 14:10:35 2023 - ERROR - oe_test_groovy_02.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ groovyc --encoding utf-8 test.groovy
oe_test_groovy_02.sh: line 45: groovyc: command not found
+ CHECK_RESULT 127 0 0 'Check groovyc --encoding failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check groovyc --encoding failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check groovyc --encoding failed.'
+ LOG_ERROR 'Check groovyc --encoding failed.'
+ message='Check groovyc --encoding failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc --encoding failed.'
Wed Apr  5 14:10:36 2023 - ERROR - Check groovyc --encoding failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 46'
+ message='oe_test_groovy_02.sh line 46'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 46'
Wed Apr  5 14:10:37 2023 - ERROR - oe_test_groovy_02.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f test.class
+ CHECK_RESULT 1 0 0 'Check groovyc --encoding failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovyc --encoding failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovyc --encoding failed.'
+ LOG_ERROR 'Check groovyc --encoding failed.'
+ message='Check groovyc --encoding failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc --encoding failed.'
Wed Apr  5 14:10:38 2023 - ERROR - Check groovyc --encoding failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 48'
+ message='oe_test_groovy_02.sh line 48'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 48'
Wed Apr  5 14:10:38 2023 - ERROR - oe_test_groovy_02.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ groovyc --indy test.groovy
oe_test_groovy_02.sh: line 49: groovyc: command not found
+ CHECK_RESULT 127 0 0 'Check groovyc --indy failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check groovyc --indy failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check groovyc --indy failed.'
+ LOG_ERROR 'Check groovyc --indy failed.'
+ message='Check groovyc --indy failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovyc --indy failed.'
Wed Apr  5 14:10:39 2023 - ERROR - Check groovyc --indy failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 50'
+ message='oe_test_groovy_02.sh line 50'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 50'
Wed Apr  5 14:10:40 2023 - ERROR - oe_test_groovy_02.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f test.class
+ CHECK_RESULT 1 0 0 'Check test.class not exist.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check test.class not exist.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check test.class not exist.'
+ LOG_ERROR 'Check test.class not exist.'
+ message='Check test.class not exist.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check test.class not exist.'
Wed Apr  5 14:10:41 2023 - ERROR - Check test.class not exist.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 52'
+ message='oe_test_groovy_02.sh line 52'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 52'
Wed Apr  5 14:10:41 2023 - ERROR - oe_test_groovy_02.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 15
+ groovy test
oe_test_groovy_02.sh: line 53: groovy: command not found
+ CHECK_RESULT 1 0 0 'Check groovy failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovy failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovy failed.'
+ LOG_ERROR 'Check groovy failed.'
+ message='Check groovy failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovy failed.'
Wed Apr  5 14:10:42 2023 - ERROR - Check groovy failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 54'
+ message='oe_test_groovy_02.sh line 54'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 54'
Wed Apr  5 14:10:43 2023 - ERROR - oe_test_groovy_02.sh line 54
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f test.class
+ CHECK_RESULT 1 0 0 'Check groovy failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovy failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovy failed.'
+ LOG_ERROR 'Check groovy failed.'
+ message='Check groovy failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovy failed.'
Wed Apr  5 14:10:44 2023 - ERROR - Check groovy failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 56'
+ message='oe_test_groovy_02.sh line 56'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 56'
Wed Apr  5 14:10:44 2023 - ERROR - oe_test_groovy_02.sh line 56
+ '[' 0 -eq 1 ']'
+ return 0
+ groovydoc --help
+ grep 'usage: groovydoc'
oe_test_groovy_02.sh: line 57: groovydoc: command not found
+ CHECK_RESULT 1 0 0 'Check groovydoc --help failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovydoc --help failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovydoc --help failed.'
+ LOG_ERROR 'Check groovydoc --help failed.'
+ message='Check groovydoc --help failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovydoc --help failed.'
Wed Apr  5 14:10:45 2023 - ERROR - Check groovydoc --help failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 58'
+ message='oe_test_groovy_02.sh line 58'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 58'
Wed Apr  5 14:10:46 2023 - ERROR - oe_test_groovy_02.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ groovydoc --version
+ grep GroovyDoc
oe_test_groovy_02.sh: line 59: groovydoc: command not found
+ CHECK_RESULT 1 0 0 'Check groovydoc --version failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check groovydoc --version failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check groovydoc --version failed.'
+ LOG_ERROR 'Check groovydoc --version failed.'
+ message='Check groovydoc --version failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovydoc --version failed.'
Wed Apr  5 14:10:47 2023 - ERROR - Check groovydoc --version failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 60'
+ message='oe_test_groovy_02.sh line 60'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 60'
Wed Apr  5 14:10:47 2023 - ERROR - oe_test_groovy_02.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ groovydoc test.groovy
oe_test_groovy_02.sh: line 61: groovydoc: command not found
++ ls ./
++ wc -w
+ CHECK_RESULT 2 14
+ actual_result=2
+ expect_result=14
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 14x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 62'
+ message='oe_test_groovy_02.sh line 62'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 62'
Wed Apr  5 14:10:48 2023 - ERROR - oe_test_groovy_02.sh line 62
+ '[' 0 -eq 1 ']'
+ return 0
+ groovydoc -d /tmp ./test.groovy
oe_test_groovy_02.sh: line 63: groovydoc: command not found
+ CHECK_RESULT 127 0 0 'Check groovydoc -d failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Check groovydoc -d failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Check groovydoc -d failed.'
+ LOG_ERROR 'Check groovydoc -d failed.'
+ message='Check groovydoc -d failed.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'Check groovydoc -d failed.'
Wed Apr  5 14:10:49 2023 - ERROR - Check groovydoc -d failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 64'
+ message='oe_test_groovy_02.sh line 64'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 64'
Wed Apr  5 14:10:50 2023 - ERROR - oe_test_groovy_02.sh line 64
+ '[' 0 -eq 1 ']'
+ return 0
++ ls /tmp/
++ wc -w
+ CHECK_RESULT 7 15
+ actual_result=7
+ expect_result=15
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 7 ']'
+ '[' 0 -eq 0 ']'
+ test 7x '!=' 15x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_groovy_02.sh line 65'
+ message='oe_test_groovy_02.sh line 65'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_groovy_02.sh line 65'
Wed Apr  5 14:10:50 2023 - ERROR - oe_test_groovy_02.sh line 65
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Apr  5 14:10:51 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 18
+ test 18 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 14:10:52 2023 - ERROR - failed to execute the case.
+ exit 18
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Apr  5 14:10:53 2023 - INFO  - Start to restore the test environment.
++ ls
++ grep -v '\.sh'
+ rm -rf test.groovy /tmp/systemd-private-c346795603324977936aa70f4935cec6-rtkit-daemon.service-ZJqk99 /tmp/systemd-private-c346795603324977936aa70f4935cec6-systemd-coredump@60-1688-0.service-I0a08t /tmp/systemd-private-c346795603324977936aa70f4935cec6-systemd-logind.service-D4yghA /tmp/systemd-private-c346795603324977936aa70f4935cec6-systemd-timesyncd.service-LeOyWt /tmp/systemd-private-c346795603324977936aa70f4935cec6-upower.service-nK1Yyk /tmp/tmp0_nu1k3b /tmp/tmpsuyk9tey
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 14:08:03 ago on Wed 05 Apr 2023 12:02:19 AM CST.
Error: 
 Problem: conflicting requests
  - nothing provides mvn(jline:jline) needed by groovy-2.4.8-11.oe2303.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 14:08:03 ago on Wed 05 Apr 2023 12:02:19 AM CST.
Error: 
 Problem: conflicting requests
  - nothing provides mvn(jline:jline) needed by groovy-2.4.8-11.oe2303.noarch
(try to add '\''--skip-broken'\'' to skip uninstallable packages or '\''--nobest'\'' to use not only best candidate packages)'
Traceback (most recent call last):
  File "/root/GitRepo/mugen/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 14:08:03 ago on Wed 05 Apr 2023 12:02:19 AM CST.\nError: \n Problem: conflicting requests\n  - nothing provides mvn(jline:jline) needed by groovy-2.4.8-11.oe2303.noarch\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/GitRepo/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Apr  5 14:10:57 2023 - INFO  - End to restore the test environment.
